#ifndef FLAPPY_BIRD_COMPONENTS_PAUSE_ELEMENT_H
#define FLAPPY_BIRD_COMPONENTS_PAUSE_ELEMENT_H

class PauseElement {
 public:
  void draw() const;
};

#endif  // FLAPPY_BIRD_COMPONENTS_PAUSE_ELEMENT_H
